apiVersion: v1
kind: Service
metadata:
  name: mdeforge-project-service
  labels:
    application: mdeforge
    app: mdeforge
spec:
  ports:
  - name: httpport
    port: 8080
    targetPort: 8080
  selector:
    svc: mdeforge-project-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mdeforge-project-service
  labels:
    application: mdeforge
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: mdeforge-project-service
        application: mdeforge
    spec:
      containers:
      - name: project-service
        image: carloselpapa10/project-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: httpport
        env:
          - name: JAVA_OPTS
            value: "-Dsun.net.inetaddr.ttl=30"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mdeforge-mysql-service/eventuate
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mdeforge-secrets
                key: mysql_username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mdeforge-secrets
                key: mysql_password
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: mdeforge-kafka-service:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: mdeforge-zookeeper-service:2181
          - name: MONGODB
            value: mdeforge-mongodb-service:27017/projectservicedb
          - name: SPRING_BOOT_ADMIN_URL
            value: mdeforge-admin:8080
          - name: SPRING_BOOT_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: mdeforge-secrets
                key: spring_boot_admin_username
          - name: SPRING_BOOT_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mdeforge-secrets
                key: spring_boot_admin_password
          - name: SPRING_BOOT_ADMIN_CLIENT_NAME
            value: project-service
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 20
---
