apiVersion: v1
kind: Service
metadata:
  name: mdeforge-tram-cdc-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    svc: mdeforge-tram-cdc-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mdeforge-tram-cdc-service
  labels:
    application: mdeforge
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: mdeforge-tram-cdc-service
    spec:
      containers:
      - name: cdcservice
        image: eventuateio/eventuate-tram-cdc-mysql-service:0.6.0.RELEASE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: httpport
        command: ["bash", "-c", "java -Dsun.net.inetaddr.ttl=30 -jar *.jar" ]
        env:
          - name: JAVA_OPTS
            value: "-Dsun.net.inetaddr.ttl=30"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mdeforge-mysql-service/eventuate
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mdeforge-secrets
                key: mysql_username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mdeforge-secrets
                key: mysql_password
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: mdeforge-kafka-service:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: mdeforge-zookeeper-service:2181
          - name: EVENTUATELOCAL_CDC_DB_USER_NAME
            value: root
          - name: EVENTUATELOCAL_CDC_DB_PASSWORD
            value: rootpassword
          - name: EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID
            value: "1234567890"
          - name: EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME
            value: message
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
---
