apiVersion: v1
kind: Service
metadata:
  name: mdeforge-mysql-service
  labels:
    name: mdeforge-mysql-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    role: mdeforge-mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mdeforge-mysql
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        role: mdeforge-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: eventuateio/eventuate-tram-sagas-mysql:0.3.0.RELEASE
          imagePullPolicy: Always
          args:
              - "--ignore-db-dir=lost+found"
          ports:
              - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mdeforge-secrets
                  key: mysql_root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mdeforge-secrets
                  key: mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mdeforge-secrets
                  key: mysql_password
          volumeMounts:
            - name: mdeforge-mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mdeforge-mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
