apiVersion: v1
kind: Service
metadata:
  name: mdeforge-mongodb-service
  labels:
    name: mdeforge-mongodb-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mdeforge-mongodb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mdeforge-mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        role: mdeforge-mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:3.0.15
          imagePullPolicy: Always
          ports:
              - containerPort: 27017
          env:
            - name: MONGO_DATA_DIR
              value: /data/db
            - name: MONGO_LOG_DIR
              value: /dev/null
          volumeMounts:
            - name: mdeforge-mongodb-persistent-storage
              mountPath: /var/lib/mongodb
  volumeClaimTemplates:
  - metadata:
      name: mdeforge-mongodb-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
